runyan/py-sdk/05 (#12)
implement dev, prod and deploy workflows

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -18,61 +18,338 @@ orbs:
   python: circleci/python@2.0.3
 
 
+executors:
+  linux-python:
+    parameters:
+      tag:
+        type: string
+        # We intentionally let the job fail if there is no such executor so
+        # that we know the specified tag is unavailable.
+        # default: "3.8.12"
+    docker:
+      # Docker Python images
+      # https://circleci.com/developer/images/image/cimg/python#image-tags
+      - image: cimg/python:<< parameters.tag >>
+
+
 # Define a job to be invoked later in a workflow.
 # See: https://circleci.com/docs/2.0/configuration-reference/#jobs
 jobs:
-  build-and-test:
+  build-sdk:
+    description: "Build SDK"
+    parameters:
+      executor_tag:
+        description: "The Python environment that the executor uses"
+        type: string
     # You can specify an executor using an image from Dockerhub or use one of
     # the convenience images from CircleCI's Developer Hub.
     # See: https://circleci.com/docs/2.0/executor-types/
     # See: https://circleci.com/developer/images/image/cimg/python
-    docker:
-      - image: cimg/python:3.10.2
+    executor:
+      name: linux-python
+      tag: << parameters.executor_tag >>
+    working_directory: ~/repo/
     # Checkout the code as the first step. This is a dedicated CircleCI step.
     # The python orb's install-packages step will install the dependencies from
     # a Pipfile via Pipenv by default. Here we're making sure we use just use the
     # system-wide pip.
     steps:
       - checkout
-      - python/install-packages:
-          pkg-manager: pip
-          # If your requirements.txt isn't in the root directory.
-          # app-dir: ~/project/package-directory/
-          # If you have a different name for your requirements file, maybe one
-          # that combines your runtime and test requirements.
-          pip-dependency-file: requirements_dev.txt
+      # - python/install-packages:
+      #     pkg-manager: pip
+      #     # If your requirements.txt isn't in the root directory.
+      #     # app-dir: ~/project/package-directory/
+      #     # If you have a different name for your requirements file, maybe one
+      #     # that combines your runtime and test requirements.
+      #     pip-dependency-file: requirements_dev.txt
       - restore_cache:
-          key: v1-watchful-py-pkg-{{ arch }}_{{checksum "src/watchful/VERSION" }}
+          key: v1-sdk-build-deps-{{ arch }}_{{ checksum "requirements_dev.txt" }}
       - run:
-          name: Install Watchful Python Package
+          name: Install Build Deps
           command: |
-            export ____VERSION=$( cat src/watchful/VERSION )
-            printenv
-            pip3 install watchful==${____VERSION}
+            pip3 install -r requirements_dev.txt
       - save_cache:
-          key: v1-watchful-py-pkg-{{ arch }}_{{checksum "src/watchful/VERSION" }}
+          key: v1-sdk-build-deps-{{ arch }}_{{ checksum "requirements_dev.txt" }}
           paths:
-            - "~/.venv"
-            - "~/.pip"
-            - "~/.cache/pip"
-            - "~/.local/lib/python3.9"
-            - "~/.local/lib/python3.10"
+            - "/usr/local/Cellar/pyenv"
             - "~/.pyenv"
+            - "~/.cache/pip"
             - "~/Library/Caches/pip"
             - "/usr/local/lib/python3.9"
             - "/usr/local/lib/python3.10"
+            # - "~/.pip"
+            # - "~/.venv"
+            # - "~/.local/lib/python3.9"
+            # - "~/.local/lib/python3.10"
+            # - "/usr/lib/python3.9"
+            # - "/usr/lib/python3.10"
+            # - "/Library/Frameworks/Python.framework"
+            # - "/System/Library/Frameworks/Python.framework"
       - run:
-          name: Run tests
-          # This assumes pytest is installed via the install-package step above
-          # command: pytest
+          name: Build SDK
           command: |
-            pytest -W ignore::DeprecationWarning tests/test_*.py
+            export ____SDK_VERSION=$( cat src/watchful/VERSION )
+            printenv | grep ____SDK_VERSION
+            python3 -m build .
+      - store_artifacts:
+          path: dist/
+      - persist_to_workspace:
+          root: ./
+          paths:
+            - dist/
+
+  install-lint-and-test-sdk:
+    description: "Install, Lint & Test SDK"
+    parameters:
+      executor_tag:
+        description: "The Python environment that the executor uses"
+        type: string
+      sdk_location:
+        description: "Location to pull SDK from"
+        type: enum
+        enum: [ "pypi", "repo" ]
+        default: "pypi"
+      profile:
+        description: "Profile to use for tests"
+        type: enum
+        enum: [ "dev", "prod", "deploy" ]
+        default: "dev"
+    # You can specify an executor using an image from Dockerhub or use one of
+    # the convenience images from CircleCI's Developer Hub.
+    # See: https://circleci.com/docs/2.0/executor-types/
+    # See: https://circleci.com/developer/images/image/cimg/python
+    executor:
+      name: linux-python
+      tag: << parameters.executor_tag >>
+    working_directory: ~/repo/
+    steps:
+      - checkout
+      - when:
+          condition:
+            equal: [ << parameters.sdk_location >>, "repo" ]
+          steps:
+            - attach_workspace:
+                at: ~/repo
+      - when:
+          condition:
+            equal: [ << parameters.sdk_location >>, "pypi" ]
+          steps:
+            - restore_cache:
+                key: v1-sdk-deps-{{ arch }}__{{ checksum "src/watchful/VERSION" }}_{{ checksum "requirements_dev.txt" }}_{{ checksum "requirements_test.txt" }}
+      - show-python-environment
+      - run:
+          name: Install SDK
+          command: |
+            echo 'Installing SDK from << parameters.sdk_location >>...'
+            if [[ << parameters.profile >> = "dev" && << parameters.sdk_location >> = "repo" ]]; then
+              export ____SDK_VERSION=$( cat src/watchful/VERSION )
+              printenv | grep ____SDK_VERSION
+              pip3 uninstall watchful==${____SDK_VERSION} -y || true
+              pip3 show watchful | grep 'Version' || true
+              pip3 install dist/watchful-${____SDK_VERSION}-*.whl
+              pip3 show watchful | grep 'Version'
+            elif [[ << parameters.profile >> = "prod" && << parameters.sdk_location >> = "pypi" ]]; then
+              export ____SDK_VERSION_PROD_TEST=$( cat VERSION_PROD_TEST )
+              printenv | grep ____SDK_VERSION_PROD_TEST
+              pip3 uninstall watchful==${____SDK_VERSION_PROD_TEST} -y || true
+              pip3 show watchful | grep 'Version' || true
+              pip3 install watchful==${____SDK_VERSION_PROD_TEST}
+              pip3 show watchful | grep 'Version'
+            elif [[ << parameters.profile >> = "deploy" && << parameters.sdk_location >> = "repo" ]]; then
+              export ____SDK_VERSION=$( cat src/watchful/VERSION )
+              printenv | grep ____SDK_VERSION
+              pip3 uninstall watchful==${____SDK_VERSION} -y || true
+              pip3 show watchful | grep 'Version' || true
+              pip3 install dist/watchful-${____SDK_VERSION}-*.whl
+              pip3 show watchful | grep 'Version'
+            elif [[ << parameters.profile >> = "deploy" && << parameters.sdk_location >> = "pypi" ]]; then
+              export ____SDK_VERSION=$( cat src/watchful/VERSION )
+              printenv | grep ____SDK_VERSION
+              pip3 uninstall watchful==${____SDK_VERSION} -y || true
+              pip3 show watchful | grep 'Version' || true
+              echo "attempt 1..."; pip3 install watchful==${____SDK_VERSION}; sleep 3 \
+                || echo "attempt 2..."; pip3 install watchful==${____SDK_VERSION}; sleep 3 \
+                || echo "attempt 3..."; pip3 install watchful==${____SDK_VERSION}
+              pip3 show watchful | grep 'Version'
+            else
+              echo 'Path for profile=<< parameters.profile >> sdk_location=<< parameters.sdk_location >> is not implemented!'
+              exit 1
+            fi
+      - run:
+          name: Install Build Deps
+          command: |
+            pip3 install -r requirements_dev.txt
+      - run:
+          name: Install Test Deps
+          command: |
+            pip3 install -r requirements_test.txt
+      - when:
+          condition:
+            equal: [ << parameters.sdk_location >>, "pypi" ]
+          steps:
+            - save_cache:
+                key: v1-sdk-deps-{{ arch }}__{{ checksum "src/watchful/VERSION" }}_{{ checksum "requirements_dev.txt" }}_{{ checksum "requirements_test.txt" }}
+                paths:
+                  - "/usr/local/Cellar/pyenv"
+                  - "~/.pyenv"
+                  - "~/.cache/pip"
+                  - "~/Library/Caches/pip"
+                  - "/usr/local/lib/python3.9"
+                  - "/usr/local/lib/python3.10"
+                  # - "~/.pip"
+                  # - "~/.venv"
+                  # - "~/.local/lib/python3.9"
+                  # - "~/.local/lib/python3.10"
+                  # - "/usr/lib/python3.9"
+                  # - "/usr/lib/python3.10"
+                  # - "/Library/Frameworks/Python.framework"
+                  # - "/System/Library/Frameworks/Python.framework"
+      - run:
+          name: Lint SDK
+          command: |
+            pylama tests/ src/watchful/ -o pylama.ini
+      - show-python-environment
+      - run:
+          name: Run SDK Tests
+          command: |
+            if [[ << parameters.profile >> = "dev" && << parameters.sdk_location >> = "repo" \
+              || << parameters.profile >> = "prod" && << parameters.sdk_location >> = "pypi" \
+              || << parameters.profile >> = "deploy" && << parameters.sdk_location >> = "repo" \
+              || << parameters.profile >> = "deploy" && << parameters.sdk_location >> = "pypi" ]]; then
+              pip3 show watchful | grep 'Version'
+              python3 tests/test_001.py --test_env << parameters.profile >>
+              python3 -m pytest -W ignore::DeprecationWarning tests/test_*.py --test_env << parameters.profile >>
+            else
+              echo 'Path for profile=<< parameters.profile >> sdk_location=<< parameters.sdk_location >> is not implemented!'
+              exit 1
+            fi
+
+  publish-sdk:
+    description: "Publish SDK"
+    parameters:
+      executor_tag:
+        description: "The Python environment that the executor uses"
+        type: string
+    executor:
+      name: linux-python
+      tag: << parameters.executor_tag >>
+    working_directory: ~/repo/
+    steps:
+      - checkout
+      - attach_workspace:
+          at: ~/repo
+      - restore_cache:
+          key: v1-sdk-build-deps-{{ arch }}_{{ checksum "requirements_dev.txt" }}
+      - run:
+          name: Install build deps
+          command: |
+            pip3 install -r requirements_dev.txt
+      - save_cache:
+          key: v1-sdk-build-deps-{{ arch }}_{{ checksum "requirements_dev.txt" }}
+          paths:
+            - "/usr/local/Cellar/pyenv"
+            - "~/.pyenv"
+            - "~/.cache/pip"
+            - "~/Library/Caches/pip"
+            - "/usr/local/lib/python3.9"
+            - "/usr/local/lib/python3.10"
+            # - "~/.pip"
+            # - "~/.venv"
+            # - "~/.local/lib/python3.9"
+            # - "~/.local/lib/python3.10"
+            # - "/usr/lib/python3.9"
+            # - "/usr/lib/python3.10"
+            # - "/Library/Frameworks/Python.framework"
+            # - "/System/Library/Frameworks/Python.framework"
+      - show-python-environment
+      - run:
+          name: Validate Tag & Publish SDK
+          command: |
+            export ____SDK_VERSION=$( cat src/watchful/VERSION )
+            printenv | grep ____SDK_VERSION
+            echo tag=<< pipeline.git.tag >>
+            echo version=$____SDK_VERSION
+            if [[ << pipeline.git.tag >> = "v"$____SDK_VERSION ]]; then
+              echo "Tag specifies the same version in repo, publishing sdk..."
+              python3 -m twine upload dist/* -u __token__ -p $PYPI_TOKEN --verbose
+            else
+              echo "Tag does not specify the same version in repo, sdk not published."
+            fi
+
+
+commands:
+  show-python-environment:
+    description: "Show information on the Python environment"
+    steps:
+      - run:
+          name: "Show Python and PIP paths and versions"
+          command: |
+            which pip3 && pip3 -V
+            which python3 && python3 -V
 
 
 # Invoke jobs via workflows.
 # See: https://circleci.com/docs/2.0/configuration-reference/#workflows
+# There are 3 workflows here. To develop and contribute to the SDK, you would be
+# monitoring the "Dev" workflow. To test the SDK from PyPI, you would be monitoring the
+# "Prod" workflow. Finally, The "Deploy" workflow publishes the SDK.
 workflows:
-  "SDK Tests":
-    # Inside the workflow, you define the jobs you want to run.
+  # This is the workflow to develop, build and test the SDK.
+  "Dev":
     jobs:
-      - build-and-test
+      - build-sdk:
+          name: "Build SDK (Dev)"
+          executor_tag: "3.8.12"
+      - install-lint-and-test-sdk:
+          name: "Install, Lint & Test Built SDK (Dev)"
+          executor_tag: "3.8.12"
+          sdk_location: "repo"
+          profile: "dev"
+          requires:
+            - "Build SDK (Dev)"
+  # This is the workflow to test the SDK from PyPI.
+  "Prod":
+    jobs:
+      - install-lint-and-test-sdk:
+          name: "Install, Lint & Test PyPI SDK (Prod)"
+          executor_tag: "3.8.12"
+          sdk_location: "pypi"
+          profile: "prod"
+  # This is the workflow to build, publish and test the SDK from PyPI.
+  "Deploy":
+    when: << pipeline.git.tag >>
+    jobs:
+      - build-sdk:
+          name: "Build SDK (Deploy)"
+          executor_tag: "3.8.12"
+          filters:
+            tags:
+              only: /^v.*/
+      - install-lint-and-test-sdk:
+          name: "Install, Lint & Test Built SDK (Deploy)"
+          executor_tag: "3.8.12"
+          sdk_location: "repo"
+          profile: "deploy"
+          requires:
+            - "Build SDK (Deploy)"
+          filters:
+            tags:
+              only: /^v.*/
+      - publish-sdk:
+          name: "Publish SDK"
+          executor_tag: "3.8.12"
+          requires:
+            - "Install, Lint & Test Built SDK (Deploy)"
+          filters:
+            tags:
+              only: /^v.*/
+      - install-lint-and-test-sdk:
+          name: "Install, Lint & Test PyPI SDK (Deploy)"
+          executor_tag: "3.8.12"
+          sdk_location: "pypi"
+          profile: "deploy"
+          requires:
+            - "Publish SDK"
+          filters:
+            tags:
+              only: /^v.*/
